# Generated by Django 3.0.6 on 2020-05-17 12:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=500, verbose_name='Name of staff member')),
                ('position', models.CharField(choices=[('J', 'Junior'), ('S', 'Senior'), ('M', 'Manager')], default='J', max_length=1, verbose_name='Position of staff member')),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comission percentage')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name of Drink')),
                ('price_per_cup', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price per cup')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Staff')),
            ],
        ),
    ]
